export const DISPLAY_ALERT_CONFIRM = 'DISPLAY_ALERT_CONFIRM';
export const DISPLAY_ALERT_DANGER = 'DISPLAY_ALERT_DANGER';

export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const LOGOUT_USER = 'LOGOUT_USER';
