export const DISPLAY_ALERT_CONFIRM = 'DISPLAY_ALERT_CONFIRM';
export const DISPLAY_ALERT_DANGER = 'DISPLAY_ALERT_DANGER';

export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';
