export const DISPLAY_ALERT_CONFIRM = 'DISPLAY_ALERT_CONFIRM';
export const DISPLAY_ALERT_DANGER = 'DISPLAY_ALERT_DANGER';

export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';

export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';

export const CLEAR_VALUES = 'CLEAR_VALUES';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';

export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN';

export const SET_EDIT_JOB = 'SET_EDIT_JOB';
export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN';
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS';
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';

export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN';
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS';

export const CREATE_INTERVIEW_BEGIN = 'CREATE_INTERVIEW_BEGIN';
export const CREATE_INTERVIEW_SUCCESS = 'CREATE_INTERVIEW_SUCCESS';
export const CREATE_INTERVIEW_ERROR = 'CREATE_INTERVIEW_ERROR';

export const SET_EDIT_INTERVIEW = 'SET_EDIT_INTERVIEW';
export const EDIT_INTERVIEW_BEGIN = 'EDIT_INTERVIEW_BEGIN';
export const UPDATE_INTERVIEW_BEGIN = 'UPDATE_INTERVIEW_BEGIN';
export const UPDATE_INTERVIEW_SUCCESS = 'UPDATE_INTERVIEW_SUCCESS';
export const UPDATE_INTERVIEW_ERROR = 'UPDATE_INTERVIEW_ERROR';

export const GET_INTERVIEWS_BEGIN = 'GET_INTERVIEWS_BEGIN';
export const GET_INTERVIEWS_SUCCESS = 'GET_INTERVIEWS_SUCCESS';

export const DELETE_INTERVIEW_BEGIN = 'DELETE_INTERVIEW_BEGIN';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const LOGOUT_USER = 'LOGOUT_USER';
